### ISSUE TITLE
setGlobalState to return boolean

### ISSUE THREAD

**Issue by martinkfb** [foobaragency/foo-state#173]
Would be nice to have `setGlobalState` to return `boolean` if new state was set. It would require only two small changes in `foo-state` library:

- [ `setGlobalState` ](https://github.com/foobaragency/foo-state/blob/8fe0bb03d2df3d57a5ecb9c8ab10f83c400ddf58/src/Observable.ts#L36) to return boolean:  `false` in case of `deepCompare` was equal, as well as return value of
- [`Observer.next()` ](https://github.com/foobaragency/foo-state/blob/8fe0bb03d2df3d57a5ecb9c8ab10f83c400ddf58/src/Observable.ts#L36) to return boolean: `false` in case of values are equal, `true` otherwise.

With this it would be possible to evaluate if state has been set:
```
if ( setGlobalState(newState, { deepCompare: true }) ) {
  ...
}
```

WDYT?

**Comment by l-Leniac-l** [comment]
The `deepCompare` option is there to help avoid unnecessary re-renders in cases where a state is an object or array. I don't see any circumstance where returning a boolean would be helpful. Also, we're trying to keep our functions as close as possible to the React API. Even having the `deepCompare` option is kind of against that philosophy, given that the developer should check that before making the state updates as they would with the React `setState`.

@juan-foobar, WDYT?

**Comment by juan-foobar** [comment]
Well, first, thank you @martinkfb for your suggestion and trying to improve the library! 💪 ❤️ 

However, I believe @l-Leniac-l shared valid points on why this change does not seem to be on the right direction. To share a bit more context, for setting state, [React declares that we should "_think of `setState()` as a request rather than an immediate command to update the component. For better perceived performance, React may delay it, and then update several components in a single pass._"](https://reactjs.org/docs/react-component.html#setstate) This applies to the `setGlobalState` function, and therefore, we shouldn't worry about when it updates or if it's value changed, we should just be interested that it will update the state.

@martinkfb maybe you could share with us what is your intended use case, what problem are you trying to solve, or what seems not to be possible with what `foo-state` currently offers and then we can suggest a strategy or alternative approach, will this work for you?

**Comment by martinkfb** [comment]
> [..] we're trying to keep our functions as close as possible to the React API.
thanks for your explanations @l-Leniac-l @juan-foobar, I think the issue can be closed.
